export const SuccessMessages = {
  USER_CREATED_SUCCESSFULLY: 'success.USER_CREATED_SUCCESSFULLY',
  USER_UPDATED_SUCCESSFULLY: 'success.USER_UPDATED_SUCCESSFULLY',
  USER_DELETED_SUCCESSFULLY: 'success.USER_DELETED_SUCCESSFULLY',
  ROLE_CREATED_SUCCESSFULLY: 'success.ROLE_CREATED_SUCCESSFULLY',
  PERMISSION_CREATED_SUCCESSFULLY: 'success.PERMISSION_CREATED_SUCCESSFULLY',
  PERMISSION_ASSIGNED_SUCCESSFULLY: 'success.PERMISSION_ASSIGNED_SUCCESSFULLY',
};
