export const SuccessMessages = {
  USER_CREATED_SUCCESSFULLY: 'success.USER_CREATED_SUCCESSFULLY',
  USER_UPDATED_SUCCESSFULLY: 'success.USER_UPDATED_SUCCESSFULLY',
  USER_DELETED_SUCCESSFULLY: 'success.USER_DELETED_SUCCESSFULLY',
};
