export const ValidationMessages = {
  USER_DOES_NOT_EXISTS: 'validation.USER_DOES_NOT_EXISTS',
  USER_EXISTS: 'validation.USER_EXISTS',
  SOMETHING_WENT_WRONG: 'validation.SOMETHING_WENT_WRONG',
  TARGET_SHOULD_BE_VALID: 'validation.$property_SHOULD_BE_VALID',
  TARGET_SHOULD_NOT_BE_EMPTY: 'validation.$property_SHOULD_NOT_BE_EMPTY',
  TARGET_SHOULD_BE_STRING: 'validation.$property_SHOULD_BE_STRING',
  TARGET_SHOULD_BE_NUMBER: 'validation.$property_SHOULD_BE_NUMBER',
  TARGET_SHOULD_BE_BOOLEAN: 'validation.$property_SHOULD_BE_BOOLEAN',
  ROLE_EXISTS: 'validation.ROLE_EXISTS',
  ROLE_NOT_FOUND: 'validation.ROLE_NOT_FOUND',
  PERMISSION_EXISTS: 'validation.PERMISSION_EXISTS',
  PERMISSION_NOT_FOUND: 'validation.PERMISSION_NOT_FOUND',
};
